name: Deploy to one.com (SFTP)

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: ðŸš€ Deploy via SFTP (lftp)
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: ðŸ“‚ Sync files via lftp
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lftp
        
        # Mirroring to the root directory './'
        # without --size-only to ensure all files with newer git-checkout timestamps are uploaded.
        cat <<EOF > deploy.lftp
        set sftp:auto-confirm yes
        set ssl:verify-certificate no
        open sftp://$SFTP_SERVER
        user "$SFTP_USERNAME" "$SFTP_PASSWORD"
        mirror -R --verbose --exclude-glob .git/ --exclude-glob .github/ --exclude-glob *.lftp ./ ./
        bye
        EOF
        
        lftp -f deploy.lftp
