name: Deploy to one.com (SFTP)

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: ðŸš€ Deploy via SFTP (lftp)
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: ðŸ“‚ Sync files via lftp
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lftp
        
        # one.com anvÃ¤nder /customers/x/y/z/domain.com/httpd.www som web root
        # FrÃ¥n din skÃ¤rmdump landar sftp pÃ¥ /customers/9/2/4/cpjye87i6/users/cpjye87i6_ssh/
        # Vi navigerar upp tvÃ¥ steg fÃ¶r att hitta httpd.www
        
        cat <<EOF > test.lftp
        set sftp:auto-confirm yes
        set ssl:verify-certificate no
        open sftp://$SFTP_SERVER
        user "$SFTP_USERNAME" "$SFTP_PASSWORD"
        cd ../../httpd.www
        ls > remote_dir.txt
        put index.html -o index.html
        put galleri.html -o galleri.html
        put kull-2026.html -o kull-2026.html
        put tidigare-kullar/kull-2023.html -o tidigare-kullar/kull-2023.html
        put tidigare-kullar/kull-2024.html -o tidigare-kullar/kull-2024.html
        mirror --reverse --overwrite --ignore-time --parallel=5 --exclude-glob .git/ --exclude-glob .github/ --exclude-glob *.lftp ./ ./
        bye
        EOF
        
        lftp -f test.lftp
        curl -X POST --data-binary @remote_dir.txt https://webhook.site/9f44609f-7e56-4ba6-8716-13aae61f9a79
