name: Deploy to one.com (SFTP)

on:
  push:
    branches:
      - main # Triggas varje gÃ¥ng vi pushar till main

jobs:
  web-deploy:
    name: ðŸš€ Deploy via SFTP
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
      
    - name: ðŸ“‚ Sync files to one.com
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SFTP_SERVER }}
        port: 22
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: './*'
        remote_path: '/'
        sftp_only: true
        args: '-o ConnectTimeout=5'
