name: Deploy to one.com (SFTP)

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: ðŸš€ Deploy via SFTP (lftp)
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v4
        
    - name: ðŸ“‚ Sync files via lftp
      env:
        SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y lftp
        
        echo "Root dir is www" > test_www_dir.txt
        
        cat <<EOF > test.lftp
        set sftp:auto-confirm yes
        set ssl:verify-certificate no
        open sftp://$SFTP_SERVER
        user "$SFTP_USERNAME" "$SFTP_PASSWORD"
        cd www
        mirror -R --verbose --size-only --exclude .git/ --exclude .github/ ./ ./
        put test_www_dir.txt
        bye
        EOF
        
        lftp -f test.lftp
